version: '3.8'
services:
  Dewpay-FrontEnd:
    image: dewpay-frontend
    build:
      context: .
      #target: STAGE 2.
      dockerfile: ./Dockerfile
    container_name: dewpay-frontend
    volumes:
        - '/src/app'
        - '/app/node_modules'
    ports:
      - 80:80